version: '2'

services:

  web:
    build: .
    ports:
    - "5000:5000"
    environment:
    - ASTERISK_HOST=${ASTERISK_HOST}
    - ASTERISK_AMI_USERNAME=${ASTERISK_AMI_USERNAME}
    - ASTERISK_AMI_PASSWORD=${ASTERISK_AMI_PASSWORD}  
    volumes:
      - .:/app
